-- Insert a sample approved Kolibri implementation project
INSERT INTO submissions (
  organization_name,
  contact_email,
  contact_name,
  contact_phone,
  country,
  region,
  city,
  latitude,
  longitude,
  project_description,
  implementation_date,
  number_of_students,
  number_of_teachers,
  number_of_devices,
  organization_type,
  organization_website,
  years_active,
  kolibri_version,
  channels_used,
  primary_use_case,
  primary_language,
  other_languages,
  customized_content,
  challenges_faced,
  measurable_impact,
  success_stories,
  social_media_links,
  additional_notes,
  status
) VALUES (
  'Global Education Initiative',
  'sarah@globaleducation.org',
  'Sarah Johnson',
  '+55 11 9876 5432',
  'Brazil',
  'São Paulo State',
  'São Paulo',
  -23.5505,
  -46.6333,
  'Kolibri implementation across 50 schools in rural and urban Brazil, providing offline access to educational content for over 8,000 students in areas with limited internet connectivity. Focuses on K-12 math, science, and Portuguese language curriculum.',
  '2021-03-15',
  8200,
  280,
  650,
  'Non-profit organization',
  'https://globaleducation.org',
  3,
  '0.15.0',
  ARRAY['Khan Academy', 'CK-12 Foundation', 'Global Onboarding Library'],
  'Offline learning in underserved communities',
  'Portuguese',
  ARRAY['English', 'Spanish'],
  true,
  'Device maintenance, limited technical support in remote areas',
  'Students showed 35% improvement in math scores within 6 months. Teacher engagement increased significantly with ability to track student progress offline.',
  'Teachers report improved student engagement and motivation. Rural communities now have access to quality educational content previously unavailable. Strong adoption across 50 partner schools.',
  '{"twitter": "@globaledu", "facebook": "facebook.com/globaleducation", "instagram": "instagram.com/globaledu", "linkedin": "linkedin.com/company/globaledu", "website": "https://globaleducation.org/reports"}',
  'Community-driven implementation with strong local partner support. Plans to expand to 100 schools by 2025. Annual impact reports available online.',
  'approved'
);

