-- Insert a US-based sample approved Kolibri implementation project
INSERT INTO submissions (
  organization_name,
  contact_email,
  contact_name,
  contact_phone,
  country,
  region,
  city,
  latitude,
  longitude,
  project_description,
  implementation_date,
  number_of_students,
  number_of_teachers,
  number_of_devices,
  organization_type,
  organization_website,
  years_active,
  kolibri_version,
  channels_used,
  primary_use_case,
  primary_language,
  other_languages,
  customized_content,
  challenges_faced,
  measurable_impact,
  success_stories,
  social_media_links,
  additional_notes,
  status
) VALUES (
  'Digital Equity Alliance',
  'info@digitalequityalliance.org',
  'James Okafor',
  '+1 312 555 0198',
  'United States',
  'Illinois',
  'Chicago',
  41.8781,
  -87.6298,
  'Kolibri deployment across 18 Title I schools in Chicago, providing offline-first learning experiences for students in under-resourced neighborhoods. Program focuses on math and literacy intervention for grades 3-8.',
  '2022-08-01',
  3400,
  95,
  380,
  'Non-profit organization',
  'https://digitalequityalliance.org',
  2,
  '0.16.0',
  ARRAY['Khan Academy', 'CK-12 Foundation'],
  'Supplemental learning for under-resourced Title I schools',
  'English',
  ARRAY['Spanish'],
  true,
  'Device procurement, family engagement, digital literacy training for teachers',
  'Reading proficiency scores improved 22% in pilot schools after one academic year of Kolibri use.',
  'Teachers report Kolibri has transformed their ability to differentiate instruction. Students who previously had no internet access at home now have a full learning library on school-issued tablets.',
  '{"twitter": "@DigitalEquityAlly", "website": "https://digitalequityalliance.org"}',
  'Partnered with Chicago Public Schools and two local foundations. Expanding to 30 schools next academic year.',
  'approved'
),
(
  'Rural Learning Initiative',
  'hello@rurallearning.org',
  'Elena Vasquez',
  '+1 505 555 0174',
  'United States',
  'New Mexico',
  'Albuquerque',
  35.0844,
  -106.6504,
  'Kolibri-based offline learning labs serving rural and tribal communities across New Mexico. Provides curriculum-aligned content in English and Spanish to students in areas with no reliable internet.',
  '2020-06-15',
  1800,
  60,
  210,
  'Non-profit organization',
  'https://rurallearning.org',
  4,
  '0.15.0',
  ARRAY['Khan Academy', 'Global Onboarding Library', 'PhET Interactive Simulations'],
  'Offline learning for rural and tribal communities',
  'Spanish',
  ARRAY['English'],
  true,
  'Connectivity, device durability in remote settings, language localization',
  'Graduation rates in partner schools increased by 14% since program launch. Strong uptake in STEM subjects.',
  'Students in tribal communities now access science and math content in their home language. Teachers have reduced prep time and improved lesson quality.',
  '{"facebook": "Rural Learning Initiative NM", "website": "https://rurallearning.org"}',
  'Active collaboration with tribal education departments. Seeking additional Kolibri Studio content in Indigenous languages.',
  'approved'
);
