-- Insert a sample PENDING submission for admin review
INSERT INTO submissions (
  organization_name,
  contact_email,
  contact_name,
  contact_phone,
  country,
  region,
  city,
  latitude,
  longitude,
  project_description,
  implementation_date,
  number_of_students,
  number_of_teachers,
  number_of_devices,
  organization_type,
  organization_website,
  years_active,
  kolibri_version,
  channels_used,
  primary_use_case,
  primary_language,
  other_languages,
  customized_content,
  challenges_faced,
  measurable_impact,
  success_stories,
  social_media_links,
  additional_notes,
  status
) VALUES (
  'Rural Digital Learning Initiative',
  'maria.santos@rdli.org',
  'Maria Santos',
  '+52 55 1234 5678',
  'Mexico',
  'Oaxaca',
  'Santa Cruz Xoxocotlán',
  17.0256,
  -96.7336,
  'We have deployed Kolibri across 25 indigenous community schools in the mountainous regions of Oaxaca, Mexico. Our focus is on bilingual education (Spanish and Zapotec) with culturally relevant content. The implementation serves children ages 6-15 who previously had no access to digital learning resources.',
  '2024-06-01',
  1500,
  75,
  200,
  'Community-based organization',
  'https://ruraldigitallearning.org',
  1,
  '0.16.0',
  ARRAY['Khan Academy', 'Sikana', 'African Storybook'],
  'Primary education in indigenous communities',
  'Spanish',
  ARRAY['Zapotec', 'Mixtec'],
  true,
  'Electricity access is intermittent in many communities. Some teachers needed extensive training on basic computer skills before they could effectively use Kolibri.',
  'Early results show 40% increase in student attendance since Kolibri implementation. Students report higher engagement with learning materials.',
  'A 12-year-old student who had never used a computer before is now helping teach her grandmother basic reading using Kolibri content.',
  '{"twitter": "@RuralDigitalMX", "facebook": "facebook.com/RuralDigitalLearning", "website": "https://ruraldigitallearning.org/impact"}',
  'Seeking partnerships with content creators who can help develop Zapotec language learning materials. Planning to expand to 50 schools by end of 2025.',
  'pending'
);
