-- Add missing columns that the submission form collects but weren't in the original schema

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS implementation_settings TEXT[],
  ADD COLUMN IF NOT EXISTS learner_types TEXT[],
  ADD COLUMN IF NOT EXISTS device_usage TEXT[],
  ADD COLUMN IF NOT EXISTS client_devices TEXT[],
  ADD COLUMN IF NOT EXISTS server_devices TEXT[],
  ADD COLUMN IF NOT EXISTS client_device_types TEXT[],
  ADD COLUMN IF NOT EXISTS hardware_model TEXT[],
  ADD COLUMN IF NOT EXISTS blended_learning_model TEXT[],
  ADD COLUMN IF NOT EXISTS kolibri_usage_description TEXT,
  ADD COLUMN IF NOT EXISTS uses_kolibri_studio BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS testimonials TEXT,
  ADD COLUMN IF NOT EXISTS reports TEXT,
  ADD COLUMN IF NOT EXISTS twitter_handle TEXT,
  ADD COLUMN IF NOT EXISTS facebook_handle TEXT,
  ADD COLUMN IF NOT EXISTS instagram_handle TEXT,
  ADD COLUMN IF NOT EXISTS linkedin_handle TEXT,
  ADD COLUMN IF NOT EXISTS forum_username TEXT,
  ADD COLUMN IF NOT EXISTS other_social TEXT,
  ADD COLUMN IF NOT EXISTS receive_updates BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS email_visible BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS start_year INTEGER,
  ADD COLUMN IF NOT EXISTS platform_language TEXT,
  ADD COLUMN IF NOT EXISTS public_channels TEXT,
  ADD COLUMN IF NOT EXISTS channel_description TEXT,
  ADD COLUMN IF NOT EXISTS channel_token TEXT,
  ADD COLUMN IF NOT EXISTS learning_goals TEXT;
