-- Sample submissions: 3 approved, 1 pending

INSERT INTO submissions (
  status, name, email, organization_name, location, latitude, longitude,
  organization_website, start_year, implementation_settings, learner_types,
  number_of_learners, number_of_teachers, device_usage, server_devices,
  client_device_types, hardware_model, blended_learning_model,
  kolibri_usage_description, primary_language, public_channels,
  uses_kolibri_studio, photo_url, program_links, testimonials, reports,
  twitter_handle, facebook_handle, instagram_handle, linkedin_handle,
  forum_username, other_social, receive_updates, email_visible
) VALUES

-- 1. Approved – Kenya
(
  'approved',
  'Amara Osei',
  'amara.osei@elimudigital.ke',
  'Elimu Digital Kenya',
  'Kisumu, Kenya',
  -0.1022, 34.7617,
  'https://elimudigital.ke',
  '2019',
  ARRAY['School', 'Community center'],
  ARRAY['Primary school students', 'Secondary school students'],
  '340', '18',
  ARRAY['Each learner uses their own device'],
  ARRAY['Raspberry Pi'],
  ARRAY['Tablets', 'Laptops'],
  ARRAY['Raspberry Pi local server'],
  ARRAY['Flipped classroom', 'Independent practice'],
  'We use Kolibri as the primary learning platform in our school lab. Students access math and literacy content daily during structured learning periods. Teachers assign exercises and monitor progress through the coach dashboard.',
  'Swahili',
  'Khan Academy (Kolibri), CK-12, African Storybook',
  true,
  '/samples/kenya-school.jpg',
  '[{"title": "Elimu Digital Program Overview", "url": "https://elimudigital.ke/program"}, {"title": "2023 Annual Report", "url": "https://elimudigital.ke/report-2023"}]',
  'Since Kolibri came to our school, attendance has gone up and students look forward to coming to class. The content in Swahili makes a huge difference. – Parent, Kisumu',
  'https://elimudigital.ke/impact-report-2023.pdf',
  '@elimudigitalke',
  'Elimu Digital Kenya',
  '@elimudigitalke',
  'https://linkedin.com/company/elimu-digital-kenya',
  'elimu_amara',
  '',
  true,
  false
),

-- 2. Approved – India
(
  'approved',
  'Priya Nair',
  'priya@digitalpaathshala.in',
  'Digital Paathshala',
  'Rajasthan, India',
  26.9124, 75.7873,
  'https://digitalpaathshala.in',
  '2020',
  ARRAY['Community center', 'After-school program'],
  ARRAY['Primary school students', 'Out-of-school youth', 'Adults'],
  '210', '9',
  ARRAY['Learners share devices'],
  ARRAY['Old laptop repurposed as server'],
  ARRAY['Shared tablets', 'Smartphones'],
  ARRAY['Old laptop repurposed as server'],
  ARRAY['Independent practice', 'Group learning'],
  'Digital Paathshala runs after-school Kolibri sessions three days a week for children in underserved villages. We use the platform to supplement government curriculum with Hindi-language math and science content. Our volunteers serve as coaches.',
  'Hindi',
  'Khan Academy (Kolibri), RACHEL, Pratham Books',
  true,
  '/samples/india-community.jpg',
  '[{"title": "Digital Paathshala Story", "url": "https://digitalpaathshala.in/story"}]',
  'My daughter never liked studying before. Now she asks to go to the center every day because she loves the videos and exercises. – Mother, Barmer village',
  'https://digitalpaathshala.in/whitepaper.pdf',
  '@digitalpaathshala',
  'Digital Paathshala India',
  '@digitalpaathshala',
  'https://linkedin.com/company/digital-paathshala',
  'priya_paathshala',
  '',
  true,
  true
),

-- 3. Approved – Colombia
(
  'approved',
  'Carlos Mendoza',
  'cmendoza@bibliodigital.org.co',
  'BiblioDigital Colombia',
  'Chocó, Colombia',
  5.6919, -76.6583,
  'https://bibliodigital.org.co',
  '2018',
  ARRAY['School', 'Library', 'Community center'],
  ARRAY['Primary school students', 'Secondary school students', 'Adults'],
  '480', '22',
  ARRAY['Each learner uses their own device', 'Learners share devices'],
  ARRAY['Dedicated local server'],
  ARRAY['Desktop computers', 'Laptops', 'Tablets'],
  ARRAY['Dedicated local server', 'Raspberry Pi'],
  ARRAY['Teacher-led instruction', 'Independent practice', 'Remediation'],
  'BiblioDigital operates a network of community digital libraries across rural Chocó. Kolibri is installed on local servers at each site and serves as the backbone of our digital learning program. We run structured sessions for school-age children and open hours for adults seeking literacy and vocational skills.',
  'Spanish',
  'Khan Academy (Kolibri), CK-12, Wikipedia for Schools',
  true,
  '/samples/colombia-library.jpg',
  '[{"title": "BiblioDigital Network Map", "url": "https://bibliodigital.org.co/network"}, {"title": "UNESCO Case Study", "url": "https://bibliodigital.org.co/unesco-case-study"}]',
  'Kolibri has allowed us to bring quality education to communities that have never had reliable internet. The offline capability is everything for us. – Carlos Mendoza, Director',
  'https://bibliodigital.org.co/impact-2023.pdf',
  '@bibliodigitalco',
  'BiblioDigital Colombia',
  '@bibliodigital.co',
  'https://linkedin.com/company/bibliodigital-colombia',
  'carlos_bibliodigital',
  '',
  true,
  true
),

-- 4. Pending – Indonesia
(
  'pending',
  'Siti Rahayu',
  'siti.rahayu@rumahjarbelajar.id',
  'Rumah Jar Belajar',
  'West Kalimantan, Indonesia',
  0.3333, 111.5167,
  'https://rumahjarbelajar.id',
  '2022',
  ARRAY['School', 'After-school program'],
  ARRAY['Primary school students', 'Secondary school students'],
  '155', '7',
  ARRAY['Learners share devices'],
  ARRAY['Raspberry Pi'],
  ARRAY['Tablets', 'Smartphones'],
  ARRAY['Raspberry Pi local server'],
  ARRAY['Flipped classroom', 'Independent practice'],
  'Rumah Jar Belajar is a grassroots initiative bringing digital learning to remote villages in West Kalimantan. We set up Raspberry Pi servers in schools and community halls, allowing students to access Kolibri content even without internet. Sessions are facilitated by trained community volunteers.',
  'Indonesian',
  'Khan Academy (Kolibri), CK-12',
  false,
  '/samples/indonesia-school.jpg',
  '[{"title": "Rumah Jar Program Info", "url": "https://rumahjarbelajar.id/program"}]',
  'Before this program, our children had no access to digital learning tools at all. Kolibri has opened a whole new world for them. – Village head, Sintang district',
  '',
  '@rumahjarbelajar',
  'Rumah Jar Belajar',
  '@rumahjarbelajar',
  '',
  'siti_rumahjar',
  '',
  true,
  false
);
